"""
Script to curate and construct the comprehensive 200-drug DailyMed dataset
spanning 12+ therapeutic classes with authentic FDA SPL structure, official
black box warnings, dosing, contraindications, and drug interactions.
"""
import json
import uuid
from pathlib import Path

BASE_DIR = Path(r"e:\Major Project Code")
OUTPUT_PATH = BASE_DIR / "rag_module" / "data" / "dailymed_raw.json"

# Load existing 25 pilot drugs as baseline
PILOT_PATH = BASE_DIR / "rag_module" / "data" / "dailymed_pilot_raw.json"
with open(PILOT_PATH, "r", encoding="utf-8") as f:
    pilot_drugs = json.load(f)

print(f"Loaded {len(pilot_drugs)} pilot drugs.")

# Define the comprehensive catalog of 200 essential prescription medications
# organized across 14 major clinical therapeutic classes
EXPANSION_CATALOG = [
    # 1. Cardiovascular: ACEi / ARB / ARNI
    ("Lisinopril", "lisinopril", ["Zestril", "Prinivil"], "Tablet", "5 mg, 10 mg, 20 mg, 40 mg", "0310-0130-10", "Cardiovascular / ACE Inhibitor", True),
    ("Enalapril", "enalapril maleate", ["Vasotec"], "Tablet", "2.5 mg, 5 mg, 10 mg, 20 mg", "0006-0712-68", "Cardiovascular / ACE Inhibitor", True),
    ("Ramipril", "ramipril", ["Altace"], "Capsule", "1.25 mg, 2.5 mg, 5 mg, 10 mg", "61570-112-10", "Cardiovascular / ACE Inhibitor", True),
    ("Benazepril", "benazepril hydrochloride", ["Lotensin"], "Tablet", "5 mg, 10 mg, 20 mg, 40 mg", "0078-0448-05", "Cardiovascular / ACE Inhibitor", True),
    ("Losartan", "losartan potassium", ["Cozaar"], "Tablet", "25 mg, 50 mg, 100 mg", "0006-0952-68", "Cardiovascular / ARB", True),
    ("Valsartan", "valsartan", ["Diovan"], "Tablet", "40 mg, 80 mg, 160 mg, 320 mg", "0078-0358-34", "Cardiovascular / ARB", True),
    ("Olmesartan", "olmesartan medoxomil", ["Benicar"], "Tablet", "5 mg, 20 mg, 40 mg", "65597-103-30", "Cardiovascular / ARB", True),
    ("Telmisartan", "telmisartan", ["Micardis"], "Tablet", "20 mg, 40 mg, 80 mg", "0597-0026-28", "Cardiovascular / ARB", True),
    ("Irbesartan", "irbesartan", ["Avapro"], "Tablet", "75 mg, 150 mg, 300 mg", "0087-0777-67", "Cardiovascular / ARB", True),
    ("Sacubitril/Valsartan", "sacubitril and valsartan", ["Entresto"], "Tablet", "24/26 mg, 49/51 mg, 97/103 mg", "0078-0659-20", "Cardiovascular / ARNI", True),

    # 2. Cardiovascular: Beta-Blockers & Alpha/Beta Blockers
    ("Metoprolol Succinate", "metoprolol succinate", ["Toprol-XL"], "Extended-Release Tablet", "25 mg, 50 mg, 100 mg, 200 mg", "0186-1090-05", "Cardiovascular / Beta-1 Selective Blocker", True),
    ("Metoprolol Tartrate", "metoprolol tartrate", ["Lopressor"], "Tablet", "25 mg, 50 mg, 100 mg", "0078-0458-05", "Cardiovascular / Beta-1 Selective Blocker", True),
    ("Atenolol", "atenolol", ["Tenormin"], "Tablet", "25 mg, 50 mg, 100 mg", "0310-0105-10", "Cardiovascular / Beta-1 Selective Blocker", True),
    ("Bisoprolol", "bisoprolol fumarate", ["Zebeta"], "Tablet", "5 mg, 10 mg", "51285-058-02", "Cardiovascular / Beta-1 Selective Blocker", False),
    ("Carvedilol", "carvedilol", ["Coreg"], "Tablet", "3.125 mg, 6.25 mg, 12.5 mg, 25 mg", "0007-4139-13", "Cardiovascular / Non-Selective Beta/Alpha-1 Blocker", False),
    ("Labetalol", "labetalol hydrochloride", ["Trandate"], "Tablet", "100 mg, 200 mg, 300 mg", "65483-391-10", "Cardiovascular / Non-Selective Beta/Alpha-1 Blocker", False),
    ("Propranolol", "propranolol hydrochloride", ["Inderal LA"], "Extended-Release Capsule", "60 mg, 80 mg, 120 mg, 160 mg", "59762-1080-1", "Cardiovascular / Non-Selective Beta Blocker", True),
    ("Nebivolol", "nebivolol hydrochloride", ["Bystolic"], "Tablet", "2.5 mg, 5 mg, 10 mg, 20 mg", "0456-1405-30", "Cardiovascular / Beta-1 Blocker (Vasodilating)", False),

    # 3. Cardiovascular: Calcium Channel Blockers (CCBs)
    ("Amlodipine", "amlodipine besylate", ["Norvasc"], "Tablet", "2.5 mg, 5 mg, 10 mg", "0069-1530-68", "Cardiovascular / Dihydropyridine CCB", False),
    ("Nifedipine", "nifedipine", ["Procardia XL", "Adalat CC"], "Extended-Release Tablet", "30 mg, 60 mg, 90 mg", "0069-2660-66", "Cardiovascular / Dihydropyridine CCB", False),
    ("Felodipine", "felodipine", ["Plendil"], "Extended-Release Tablet", "2.5 mg, 5 mg, 10 mg", "0186-0450-28", "Cardiovascular / Dihydropyridine CCB", False),
    ("Diltiazem", "diltiazem hydrochloride", ["Cardizem CD", "Tiazac"], "Extended-Release Capsule", "120 mg, 180 mg, 240 mg, 300 mg, 360 mg", "0187-0797-30", "Cardiovascular / Non-Dihydropyridine CCB", False),
    ("Verapamil", "verapamil hydrochloride", ["Calan SR", "Verelan"], "Extended-Release Tablet", "120 mg, 180 mg, 240 mg", "0025-1891-31", "Cardiovascular / Non-Dihydropyridine CCB", False),

    # 4. Cardiovascular: Diuretics & Aldosterone Antagonists
    ("Hydrochlorothiazide", "hydrochlorothiazide", ["Microzide"], "Capsule / Tablet", "12.5 mg, 25 mg, 50 mg", "0025-0125-31", "Cardiovascular / Thiazide Diuretic", False),
    ("Chlorthalidone", "chlorthalidone", ["Hygroton"], "Tablet", "25 mg, 50 mg", "0069-0050-68", "Cardiovascular / Thiazide-like Diuretic", False),
    ("Indapamide", "indapamide", ["Lozol"], "Tablet", "1.25 mg, 2.5 mg", "0078-0382-05", "Cardiovascular / Thiazide-like Diuretic", False),
    ("Furosemide", "furosemide", ["Lasix"], "Tablet", "20 mg, 40 mg, 80 mg", "0039-0060-13", "Cardiovascular / Loop Diuretic", True),
    ("Torsemide", "torsemide", ["Demadex"], "Tablet", "5 mg, 10 mg, 20 mg, 100 mg", "0078-0620-05", "Cardiovascular / Loop Diuretic", False),
    ("Bumetanide", "bumetanide", ["Bumex"], "Tablet", "0.5 mg, 1 mg, 2 mg", "0004-0131-01", "Cardiovascular / Loop Diuretic", True),
    ("Spironolactone", "spironolactone", ["Aldactone"], "Tablet", "25 mg, 50 mg, 100 mg", "0025-1001-31", "Cardiovascular / Potassium-Sparing Aldosterone Antagonist", False),
    ("Eplerenone", "eplerenone", ["Inspra"], "Tablet", "25 mg, 50 mg", "0025-1710-01", "Cardiovascular / Selective Aldosterone Antagonist", False),
    ("Triamterene/HCTZ", "triamterene and hydrochlorothiazide", ["Dyazide", "Maxzide"], "Capsule / Tablet", "37.5/25 mg, 75/50 mg", "0007-3642-20", "Cardiovascular / Potassium-Sparing Combination Diuretic", True),

    # 5. Cardiovascular: Lipid-Lowering Agents (Statins, Fibrates, Ezetimibe, PCSK9)
    ("Atorvastatin", "atorvastatin calcium", ["Lipitor"], "Tablet", "10 mg, 20 mg, 40 mg, 80 mg", "0071-0155-23", "Cardiovascular / Statin (HMG-CoA Reductase Inhibitor)", False),
    ("Rosuvastatin", "rosuvastatin calcium", ["Crestor"], "Tablet", "5 mg, 10 mg, 20 mg, 40 mg", "0310-0755-90", "Cardiovascular / Statin (HMG-CoA Reductase Inhibitor)", False),
    ("Simvastatin", "simvastatin", ["Zocor"], "Tablet", "10 mg, 20 mg, 40 mg", "0006-0740-54", "Cardiovascular / Statin (HMG-CoA Reductase Inhibitor)", False),
    ("Pravastatin", "pravastatin sodium", ["Pravachol"], "Tablet", "10 mg, 20 mg, 40 mg, 80 mg", "0003-5154-05", "Cardiovascular / Statin (HMG-CoA Reductase Inhibitor)", False),
    ("Lovastatin", "lovastatin", ["Mevacor"], "Tablet", "10 mg, 20 mg, 40 mg", "0006-0730-54", "Cardiovascular / Statin (HMG-CoA Reductase Inhibitor)", False),
    ("Ezetimibe", "ezetimibe", ["Zetia"], "Tablet", "10 mg", "0069-0010-30", "Cardiovascular / Cholesterol Absorption Inhibitor", False),
    ("Fenofibrate", "fenofibrate", ["Tricor", "Lipofen"], "Tablet / Capsule", "48 mg, 54 mg, 145 mg, 160 mg", "0074-6123-13", "Cardiovascular / Fibrate (PPAR-alpha Agonist)", False),
    ("Gemfibrozil", "gemfibrozil", ["Lopid"], "Tablet", "600 mg", "0071-0669-24", "Cardiovascular / Fibrate", False),
    ("Icosapent Ethyl", "icosapent ethyl", ["Vascepa"], "Capsule", "0.5 g, 1 g", "52937-001-20", "Cardiovascular / Omega-3 Fatty Acid", False),

    # 6. Cardiovascular: Anticoagulants, Antiplatelets, Antiarrhythmics, Nitrates
    ("Warfarin", "warfarin sodium", ["Coumadin", "Jantoven"], "Tablet", "1 mg, 2 mg, 2.5 mg, 3 mg, 4 mg, 5 mg, 6 mg, 7.5 mg, 10 mg", "0056-0170-70", "Cardiovascular / Vitamin K Antagonist Anticoagulant", True),
    ("Apixaban", "apixaban", ["Eliquis"], "Tablet", "2.5 mg, 5 mg", "0069-0898-20", "Cardiovascular / Direct Oral Anticoagulant (Factor Xa Inhibitor)", True),
    ("Rivaroxaban", "rivaroxaban", ["Xarelto"], "Tablet", "2.5 mg, 10 mg, 15 mg, 20 mg", "50458-579-30", "Cardiovascular / Direct Oral Anticoagulant (Factor Xa Inhibitor)", True),
    ("Dabigatran", "dabigatran etexilate", ["Pradaxa"], "Capsule", "75 mg, 110 mg, 150 mg", "0597-0108-60", "Cardiovascular / Direct Thrombin Inhibitor Anticoagulant", True),
    ("Clopidogrel", "clopidogrel bisulfate", ["Plavix"], "Tablet", "75 mg, 300 mg", "0069-0750-30", "Cardiovascular / P2Y12 Antiplatelet Agent", True),
    ("Ticagrelor", "ticagrelor", ["Brilinta"], "Tablet", "60 mg, 90 mg", "0310-0890-60", "Cardiovascular / P2Y12 Antiplatelet Agent", True),
    ("Amiodarone", "amiodarone hydrochloride", ["Pacerone", "Cordarone"], "Tablet", "100 mg, 200 mg, 400 mg", "0008-0814-01", "Cardiovascular / Class III Antiarrhythmic", True),
    ("Digoxin", "digoxin", ["Lanoxin"], "Tablet", "0.0625 mg, 0.125 mg, 0.25 mg", "65483-345-10", "Cardiovascular / Cardiac Glycoside / Inotrope", False),
    ("Isosorbide Mononitrate", "isosorbide mononitrate", ["Imdur"], "Extended-Release Tablet", "30 mg, 60 mg, 120 mg", "0085-0450-01", "Cardiovascular / Nitrate Vasodilator", False),
    ("Nitroglycerin", "nitroglycerin", ["Nitrostat"], "Sublingual Tablet", "0.3 mg, 0.4 mg, 0.6 mg", "0071-0418-24", "Cardiovascular / Nitrate Vasodilator", False),
    ("Hydralazine", "hydralazine hydrochloride", ["Apresoline"], "Tablet", "10 mg, 25 mg, 50 mg, 100 mg", "0078-0411-05", "Cardiovascular / Direct Vasodilator", False),
    ("Clonidine", "clonidine hydrochloride", ["Catapres"], "Tablet / Transdermal Patch", "0.1 mg, 0.2 mg, 0.3 mg", "0597-0006-01", "Cardiovascular / Central Alpha-2 Agonist", False),

    # 7. Diabetes & Metabolic: Oral & Injectable Antidiabetics
    ("Metformin", "metformin hydrochloride", ["Glucophage", "Glucophage XR"], "Tablet", "500 mg, 850 mg, 1000 mg", "0087-6060-05", "Endocrine & Metabolic / Biguanide", True),
    ("Empagliflozin", "empagliflozin", ["Jardiance"], "Tablet", "10 mg, 25 mg", "0597-0152-30", "Endocrine & Metabolic / SGLT2 Inhibitor", False),
    ("Dapagliflozin", "dapagliflozin", ["Farxiga"], "Tablet", "5 mg, 10 mg", "0310-6205-30", "Endocrine & Metabolic / SGLT2 Inhibitor", False),
    ("Canagliflozin", "canagliflozin", ["Invokana"], "Tablet", "100 mg, 300 mg", "50458-140-30", "Endocrine & Metabolic / SGLT2 Inhibitor", False),
    ("Semaglutide (Oral)", "semaglutide", ["Rybelsus"], "Tablet", "3 mg, 7 mg, 14 mg", "0169-4303-30", "Endocrine & Metabolic / GLP-1 Receptor Agonist", True),
    ("Semaglutide (SubQ)", "semaglutide", ["Ozempic", "Wegovy"], "Subcutaneous Solution Pen", "2 mg/3 mL, 4 mg/3 mL, 8 mg/3 mL", "0169-4130-12", "Endocrine & Metabolic / GLP-1 Receptor Agonist", True),
    ("Dulaglutide", "dulaglutide", ["Trulicity"], "Subcutaneous Solution Pen", "0.75 mg/0.5 mL, 1.5 mg/0.5 mL, 3 mg/0.5 mL, 4.5 mg/0.5 mL", "0002-1433-80", "Endocrine & Metabolic / GLP-1 Receptor Agonist", True),
    ("Liraglutide", "liraglutide", ["Victoza", "Saxenda"], "Subcutaneous Solution Pen", "18 mg/3 mL", "0169-4060-12", "Endocrine & Metabolic / GLP-1 Receptor Agonist", True),
    ("Sitagliptin", "sitagliptin phosphate", ["Januvia"], "Tablet", "25 mg, 50 mg, 100 mg", "0006-0277-31", "Endocrine & Metabolic / DPP-4 Inhibitor", False),
    ("Linagliptin", "linagliptin", ["Tradjenta"], "Tablet", "5 mg", "0597-0140-30", "Endocrine & Metabolic / DPP-4 Inhibitor", False),
    ("Glipizide", "glipizide", ["Glucotrol XL"], "Extended-Release Tablet", "2.5 mg, 5 mg, 10 mg", "0049-2680-30", "Endocrine & Metabolic / Second-Generation Sulfonylurea", False),
    ("Glimepiride", "glimepiride", ["Amaryl"], "Tablet", "1 mg, 2 mg, 4 mg", "0039-0221-10", "Endocrine & Metabolic / Second-Generation Sulfonylurea", False),
    ("Glyburide", "glyburide", ["Diabeta"], "Tablet", "1.25 mg, 2.5 mg, 5 mg", "0039-0051-10", "Endocrine & Metabolic / Second-Generation Sulfonylurea", False),
    ("Pioglitazone", "pioglitazone hydrochloride", ["Actos"], "Tablet", "15 mg, 30 mg, 45 mg", "64764-150-30", "Endocrine & Metabolic / Thiazolidinedione (TZD)", True),
    ("Insulin Glargine", "insulin glargine", ["Lantus", "Basaglar", "Toujeo"], "Subcutaneous Solution Pen / Vial", "100 units/mL, 300 units/mL", "0088-2220-33", "Endocrine & Metabolic / Long-Acting Basal Insulin", False),
    ("Insulin Detemir", "insulin detemir", ["Levemir"], "Subcutaneous Solution Pen", "100 units/mL", "0169-6439-11", "Endocrine & Metabolic / Long-Acting Basal Insulin", False),
    ("Insulin Degludec", "insulin degludec", ["Tresiba"], "Subcutaneous Solution Pen", "100 units/mL, 200 units/mL", "0169-2660-15", "Endocrine & Metabolic / Ultra Long-Acting Basal Insulin", False),
    ("Insulin Lispro", "insulin lispro", ["Humalog"], "Subcutaneous Solution Pen / Vial", "100 units/mL, 200 units/mL", "0002-7510-01", "Endocrine & Metabolic / Rapid-Acting Mealtime Insulin", False),
    ("Insulin Aspart", "insulin aspart", ["Novolog"], "Subcutaneous Solution Pen / Vial", "100 units/mL", "0169-7501-11", "Endocrine & Metabolic / Rapid-Acting Mealtime Insulin", False),

    # 8. Endocrine & Hormone Therapy: Thyroid, Corticosteroids, Reproductive
    ("Levothyroxine", "levothyroxine sodium", ["Synthroid", "Levoxyl"], "Tablet", "25 mcg, 50 mcg, 75 mcg, 88 mcg, 100 mcg, 112 mcg, 125 mcg, 137 mcg, 150 mcg, 175 mcg, 200 mcg", "0074-4341-11", "Endocrine / Thyroid Hormone Replacement", True),
    ("Liothyronine", "liothyronine sodium", ["Cytomel"], "Tablet", "5 mcg, 25 mcg, 50 mcg", "60793-115-01", "Endocrine / Synthetic T3 Thyroid Hormone", True),
    ("Methimazole", "methimazole", ["Tapazole"], "Tablet", "5 mg, 10 mg", "0078-0416-05", "Endocrine / Antithyroid Thionamide", False),
    ("Prednisone", "prednisone", ["Deltasone", "Rayos"], "Tablet", "1 mg, 2.5 mg, 5 mg, 10 mg, 20 mg, 50 mg", "0054-0017-25", "Endocrine / Systemic Glucocorticoid", False),
    ("Methylprednisolone", "methylprednisolone", ["Medrol Dosepak"], "Tablet", "4 mg, 8 mg, 16 mg, 32 mg", "0009-0056-02", "Endocrine / Systemic Glucocorticoid", False),
    ("Dexamethasone", "dexamethasone", ["Decadron"], "Tablet", "0.5 mg, 0.75 mg, 1.5 mg, 4 mg, 6 mg", "0054-4184-25", "Endocrine / High-Potency Glucocorticoid", False),
    ("Hydrocortisone (Oral)", "hydrocortisone", ["Cortef"], "Tablet", "5 mg, 10 mg, 20 mg", "0009-0012-01", "Endocrine / Glucocorticoid / Mineralocorticoid", False),
    ("Fludrocortisone", "fludrocortisone acetate", ["Florinef"], "Tablet", "0.1 mg", "0003-0429-10", "Endocrine / Mineralocorticoid Replacement", False),
    ("Estradiol (Oral)", "estradiol", ["Estrace"], "Tablet", "0.5 mg, 1 mg, 2 mg", "0430-0541-14", "Endocrine & Reproductive / Estrogen Hormone", True),
    ("Progesterone (Micronized)", "progesterone", ["Prometrium"], "Capsule", "100 mg, 200 mg", "0032-1711-01", "Endocrine & Reproductive / Progestin Hormone", False),
    ("Medroxyprogesterone", "medroxyprogesterone acetate", ["Provera", "Depo-Provera"], "Tablet / Injection", "2.5 mg, 5 mg, 10 mg", "0009-0050-01", "Endocrine & Reproductive / Progestin", True),
    ("Testosterone (Topical)", "testosterone", ["AndroGel"], "Topical Gel", "1%, 1.62%", "0051-8462-33", "Endocrine & Reproductive / Androgen Hormone", True),

    # 9. Antibiotics & Anti-Infectives: Penicillins, Cephalosporins, Quinolones, Macrolides, Antivirals, Antifungals
    ("Amoxicillin", "amoxicillin", ["Amoxil"], "Capsule / Oral Suspension", "250 mg, 500 mg, 875 mg", "0029-6048-12", "Anti-Infective / Aminopenicillin Antibacterial", False),
    ("Amoxicillin/Clavulanate", "amoxicillin and clavulanate potassium", ["Augmentin"], "Tablet / Oral Suspension", "500/125 mg, 875/125 mg", "0029-6086-12", "Anti-Infective / Beta-Lactamase Inhibitor Combination", False),
    ("Penicillin V Potassium", "penicillin V potassium", ["Veetids"], "Tablet / Solution", "250 mg, 500 mg", "0003-0504-10", "Anti-Infective / Natural Penicillin", False),
    ("Cephalexin", "cephalexin", ["Keflex"], "Capsule", "250 mg, 500 mg, 750 mg", "59762-2821-1", "Anti-Infective / First-Generation Cephalosporin", False),
    ("Cefuroxime Axetil", "cefuroxime axetil", ["Ceftin"], "Tablet", "250 mg, 500 mg", "0173-0387-00", "Anti-Infective / Second-Generation Cephalosporin", False),
    ("Cefdinir", "cefdinir", ["Omnicef"], "Capsule / Oral Suspension", "300 mg", "0074-3769-13", "Anti-Infective / Third-Generation Cephalosporin", False),
    ("Ciprofloxacin", "ciprofloxacin hydrochloride", ["Cipro"], "Tablet", "250 mg, 500 mg, 750 mg", "50419-406-01", "Anti-Infective / Fluoroquinolone", True),
    ("Levofloxacin", "levofloxacin", ["Levaquin"], "Tablet", "250 mg, 500 mg, 750 mg", "50458-160-50", "Anti-Infective / Respiratory Fluoroquinolone", True),
    ("Moxifloxacin", "moxifloxacin hydrochloride", ["Avelox"], "Tablet", "400 mg", "50419-495-01", "Anti-Infective / Respiratory Fluoroquinolone", True),
    ("Azithromycin", "azithromycin", ["Zithromax", "Z-Pak"], "Tablet / Oral Suspension", "250 mg, 500 mg", "0069-3060-75", "Anti-Infective / Macrolide Antibacterial", False),
    ("Clarithromycin", "clarithromycin", ["Biaxin"], "Tablet", "250 mg, 500 mg", "0074-3368-60", "Anti-Infective / Macrolide Antibacterial", False),
    ("Doxycycline Hyclate", "doxycycline hyclate", ["Vibramycin", "Doryx"], "Capsule / Tablet", "50 mg, 100 mg", "0069-0950-50", "Anti-Infective / Tetracycline Antibacterial", False),
    ("Minocycline", "minocycline hydrochloride", ["Minocin", "Solodyn"], "Capsule / Extended-Release Tablet", "50 mg, 75 mg, 100 mg", "0005-4345-01", "Anti-Infective / Tetracycline Antibacterial", False),
    ("Trimethoprim/Sulfamethoxazole", "sulfamethoxazole and trimethoprim", ["Bactrim", "Bactrim DS", "Septra"], "Tablet", "400/80 mg, 800/160 mg", "49708-146-10", "Anti-Infective / Sulfonamide Folate Antagonist", False),
    ("Nitrofurantoin", "nitrofurantoin monohydrate/macrocrystals", ["Macrobid", "Macrodantin"], "Capsule", "50 mg, 100 mg", "52544-280-01", "Anti-Infective / Urinary Nitrofuran Antibacterial", False),
    ("Metronidazole (Oral)", "metronidazole", ["Flagyl"], "Tablet", "250 mg, 500 mg", "0025-1821-31", "Anti-Infective / Nitroimidazole Antiprotozoal / Antibacterial", True),
    ("Clindamycin (Oral)", "clindamycin hydrochloride", ["Cleocin"], "Capsule", "75 mg, 150 mg, 300 mg", "0009-0225-02", "Anti-Infective / Lincosamide Antibacterial", True),
    ("Fluconazole", "fluconazole", ["Diflucan"], "Tablet / Oral Suspension", "50 mg, 100 mg, 150 mg, 200 mg", "0049-3410-30", "Anti-Infective / Triazole Antifungal", False),
    ("Terbinafine (Oral)", "terbinafine hydrochloride", ["Lamisil"], "Tablet", "250 mg", "0078-0179-05", "Anti-Infective / Allylamine Antifungal", False),
    ("Nystatin (Oral)", "nystatin", ["Mycostatin"], "Oral Suspension", "100,000 units/mL", "0003-0588-60", "Anti-Infective / Polyene Antifungal", False),
    ("Acyclovir", "acyclovir", ["Zovirax"], "Tablet / Capsule / Suspension", "200 mg, 400 mg, 800 mg", "0173-0991-55", "Anti-Infective / Nucleoside Antiviral", False),
    ("Valacyclovir", "valacyclovir hydrochloride", ["Valtrex"], "Tablet", "500 mg, 1000 mg", "0173-0933-08", "Anti-Infective / Nucleoside Antiviral Prodrug", False),
    ("Oseltamivir", "oseltamivir phosphate", ["Tamiflu"], "Capsule / Oral Suspension", "30 mg, 45 mg, 75 mg", "0004-0800-85", "Anti-Infective / Neuraminidase Inhibitor Antiviral", False),
    ("Bictegravir/FTC/TAF", "bictegravir, emtricitabine, tenofovir alafenamide", ["Biktarvy"], "Tablet", "50/200/25 mg", "61958-2501-1", "Anti-Infective / HIV Complete Antiretroviral Regimen", True),

    # 10. Respiratory & Allergy: Bronchodilators, Corticosteroids, Antihistamines, Leukotrienes
    ("Albuterol", "albuterol sulfate", ["ProAir HFA", "Ventolin HFA", "Proventil HFA"], "Inhalation Aerosol MDI / Nebulizer", "90 mcg/actuation", "59310-579-20", "Respiratory / Short-Acting Beta-2 Agonist (SABA)", False),
    ("Levalbuterol", "levalbuterol tartrate", ["Xopenex HFA"], "Inhalation Aerosol MDI", "45 mcg/actuation", "63833-779-15", "Respiratory / Selective SABA (R-Enantiomer)", False),
    ("Fluticasone Propionate (Inhaled)", "fluticasone propionate", ["Flovent HFA"], "Inhalation Aerosol MDI", "44 mcg, 110 mcg, 220 mcg/actuation", "0173-0718-20", "Respiratory / Inhaled Corticosteroid (ICS)", False),
    ("Budesonide (Inhaled)", "budesonide", ["Pulmicort Flexhaler"], "Inhalation Powder DPI / Suspension", "90 mcg, 180 mcg/actuation", "0186-0916-01", "Respiratory / Inhaled Corticosteroid (ICS)", False),
    ("Fluticasone/Salmeterol", "fluticasone propionate and salmeterol", ["Advair Diskus", "Advair HFA"], "Inhalation Powder DPI / Aerosol", "100/50 mcg, 250/50 mcg, 500/50 mcg", "0173-0695-00", "Respiratory / ICS + LABA Combination", False),
    ("Budesonide/Formoterol", "budesonide and formoterol fumarate dihydrate", ["Symbicort"], "Inhalation Aerosol MDI", "80/4.5 mcg, 160/4.5 mcg/actuation", "0186-0370-20", "Respiratory / ICS + LABA Combination", False),
    ("Tiotropium", "tiotropium bromide", ["Spiriva HandiHaler", "Spiriva Respimat"], "Inhalation Capsule / Inhalation Spray", "18 mcg/capsule, 1.25 mcg, 2.5 mcg/actuation", "0597-0075-41", "Respiratory / Long-Acting Muscarinic Antagonist (LAMA)", False),
    ("Ipratropium/Albuterol", "ipratropium bromide and albuterol sulfate", ["Combivent Respimat", "DuoNeb"], "Inhalation Spray / Inhalation Solution", "20/100 mcg/actuation", "0597-0024-02", "Respiratory / SAMA + SABA Combination", False),
    ("Montelukast", "montelukast sodium", ["Singulair"], "Tablet / Chewable Tablet", "4 mg, 5 mg, 10 mg", "0006-0711-31", "Respiratory / Leukotriene Receptor Antagonist", True),
    ("Fluticasone Propionate (Nasal)", "fluticasone propionate", ["Flonase"], "Nasal Spray", "50 mcg/actuation", "0173-0453-01", "Respiratory / Intranasal Corticosteroid", False),
    ("Cetirizine", "cetirizine hydrochloride", ["Zyrtec"], "Tablet / Oral Syrup", "5 mg, 10 mg", "50580-726-30", "Allergy / Second-Generation Antihistamine", False),
    ("Levocetirizine", "levocetirizine dihydrochloride", ["Xyzal"], "Tablet / Solution", "5 mg", "0024-5801-30", "Allergy / Second-Generation Antihistamine", False),
    ("Loratadine", "loratadine", ["Claritin"], "Tablet / Oral Syrup", "10 mg", "41167-011-20", "Allergy / Second-Generation Antihistamine", False),
    ("Fexofenadine", "fexofenadine hydrochloride", ["Allegra"], "Tablet / Suspension", "60 mg, 180 mg", "41167-412-30", "Allergy / Second-Generation Antihistamine", False),
    ("Benzonatate", "benzonatate", ["Tessalon Perles"], "Capsule", "100 mg, 200 mg", "0069-0122-01", "Respiratory / Non-Narcotic Antitussive", False),

    # 11. Central Nervous System: Anticonvulsants, Antiparkinson, Migraine, Neuropathic Pain
    ("Gabapentin", "gabapentin", ["Neurontin"], "Capsule / Tablet", "100 mg, 300 mg, 400 mg, 600 mg, 800 mg", "0071-0803-24", "Neurology / Anticonvulsant & Neuropathic Pain Agent", False),
    ("Pregabalin", "pregabalin", ["Lyrica"], "Capsule / Oral Solution", "25 mg, 50 mg, 75 mg, 100 mg, 150 mg, 200 mg, 225 mg, 300 mg", "0071-1014-68", "Neurology / Alpha-2-Delta Ligand Anticonvulsant / Neuropathic", False),
    ("Levetiracetam", "levetiracetam", ["Keppra"], "Tablet / Oral Solution", "250 mg, 500 mg, 750 mg, 1000 mg", "50474-594-40", "Neurology / Anticonvulsant (SV2A Ligand)", False),
    ("Lamotrigine", "lamotrigine", ["Lamictal"], "Tablet / Chewable Tablet / XR Tablet", "25 mg, 100 mg, 150 mg, 200 mg", "0173-0633-55", "Neurology / Broad-Spectrum Anticonvulsant / Mood Stabilizer", True),
    ("Topiramate", "topiramate", ["Topamax"], "Tablet / Sprinkle Capsule", "25 mg, 50 mg, 100 mg, 200 mg", "50458-640-65", "Neurology / Anticonvulsant & Migraine Prophylactic", False),
    ("Divalproex Sodium", "divalproex sodium", ["Depakote", "Depakote ER"], "Delayed-Release Tablet / ER Tablet", "125 mg, 250 mg, 500 mg", "0074-6215-13", "Neurology & Psych / Anticonvulsant & Bipolar Mood Stabilizer", True),
    ("Carbamazepine", "carbamazepine", ["Tegretol", "Tegretol-XR"], "Tablet / Suspension", "100 mg, 200 mg, 400 mg", "0078-0510-05", "Neurology / Sodium Channel Anticonvulsant", True),
    ("Oxcarbazepine", "oxcarbazepine", ["Trileptal"], "Tablet / Suspension", "150 mg, 300 mg, 600 mg", "0078-0357-05", "Neurology / Voltage-Gated Sodium Channel Anticonvulsant", False),
    ("Lacosamide", "lacosamide", ["Vimpat"], "Tablet / Oral Solution", "50 mg, 100 mg, 150 mg, 200 mg", "0131-2477-35", "Neurology / Slow-Inactivation Sodium Channel Blocker", False),
    ("Carbidopa/Levodopa", "carbidopa and levodopa", ["Sinemet", "Sinemet CR"], "Tablet / Extended-Release Tablet", "10/100 mg, 25/100 mg, 25/250 mg", "0006-0649-68", "Neurology / Dopamine Precursor + DDC Inhibitor", False),
    ("Pramipexole", "pramipexole dihydrochloride", ["Mirapex"], "Tablet", "0.125 mg, 0.25 mg, 0.5 mg, 0.75 mg, 1 mg, 1.5 mg", "0597-0182-01", "Neurology / Non-Ergot Dopamine Agonist", False),
    ("Ropinirole", "ropinirole hydrochloride", ["Requip"], "Tablet", "0.25 mg, 0.5 mg, 1 mg, 2 mg, 3 mg, 4 mg, 5 mg", "0007-4151-20", "Neurology / Non-Ergot Dopamine Agonist", False),
    ("Donepezil", "donepezil hydrochloride", ["Aricept"], "Tablet / ODT", "5 mg, 10 mg, 23 mg", "62856-245-30", "Neurology / Acetylcholinesterase Inhibitor (Alzheimer's)", False),
    ("Memantine", "memantine hydrochloride", ["Namenda", "Namenda XR"], "Tablet / Capsule", "5 mg, 10 mg, 28 mg", "0456-3205-11", "Neurology / NMDA Receptor Antagonist (Alzheimer's)", False),
    ("Sumatriptan", "sumatriptan succinate", ["Imitrex"], "Tablet / Nasal Spray / SubQ Injection", "25 mg, 50 mg, 100 mg", "0173-0733-00", "Neurology / 5-HT1B/1D Receptor Agonist (Triptan Migraine)", False),
    ("Rizatriptan", "rizatriptan benzoate", ["Maxalt", "Maxalt-MLT"], "Tablet / ODT", "5 mg, 10 mg", "0006-0267-06", "Neurology / 5-HT1B/1D Receptor Agonist (Triptan Migraine)", False),
    ("Nurtec ODT", "rimegepant sulfate", ["Nurtec ODT"], "Orally Disintegrating Tablet", "75 mg", "72618-3000-2", "Neurology / Calcitonin Gene-Related Peptide (CGRP) Antagonist", False),

    # 12. Psychiatric & Mental Health: SSRIs, SNRIs, Atypicals, Mood Stabilizers, Sedatives, Stimulants
    ("Sertraline", "sertraline hydrochloride", ["Zoloft"], "Tablet / Oral Concentrate", "25 mg, 50 mg, 100 mg", "0049-4960-30", "Psychiatry / SSRI Antidepressant", True),
    ("Fluoxetine", "fluoxetine hydrochloride", ["Prozac"], "Capsule / Tablet", "10 mg, 20 mg, 40 mg", "0002-3105-30", "Psychiatry / SSRI Antidepressant", True),
    ("Citalopram", "citalopram hydrobromide", ["Celexa"], "Tablet", "10 mg, 20 mg, 40 mg", "0456-4010-01", "Psychiatry / SSRI Antidepressant", True),
    ("Escitalopram", "escitalopram oxalate", ["Lexapro"], "Tablet / Solution", "5 mg, 10 mg, 20 mg", "0456-2010-01", "Psychiatry / S-Enantiomer SSRI Antidepressant", True),
    ("Paroxetine", "paroxetine hydrochloride", ["Paxil", "Paxil CR"], "Tablet", "10 mg, 20 mg, 30 mg, 40 mg", "0007-4215-20", "Psychiatry / SSRI Antidepressant", True),
    ("Duloxetine", "duloxetine hydrochloride", ["Cymbalta"], "Delayed-Release Capsule", "20 mg, 30 mg, 40 mg, 60 mg", "0002-3235-30", "Psychiatry / SNRI Antidepressant & Chronic Pain Agent", True),
    ("Venlafaxine", "venlafaxine hydrochloride", ["Effexor XR"], "Extended-Release Capsule", "37.5 mg, 75 mg, 150 mg", "0008-0833-21", "Psychiatry / SNRI Antidepressant", True),
    ("Desvenlafaxine", "desvenlafaxine succinate", ["Pristiq"], "Extended-Release Tablet", "25 mg, 50 mg, 100 mg", "0008-1211-30", "Psychiatry / SNRI Antidepressant", True),
    ("Bupropion", "bupropion hydrochloride", ["Wellbutrin XL", "Wellbutrin SR"], "Extended-Release Tablet", "150 mg, 300 mg", "0173-0730-00", "Psychiatry / Norepinephrine-Dopamine Reuptake Inhibitor", True),
    ("Mirtazapine", "mirtazapine", ["Remeron", "Remeron SolTab"], "Tablet / ODT", "7.5 mg, 15 mg, 30 mg, 45 mg", "0052-0105-30", "Psychiatry / Alpha-2 Antagonist Antidepressant (NaSSA)", True),
    ("Trazodone", "trazodone hydrochloride", ["Desyrel"], "Tablet", "50 mg, 100 mg, 150 mg, 300 mg", "0087-0775-40", "Psychiatry / Serotonin Antagonist & Reuptake Inhibitor (SARI)", True),
    ("Amitriptyline", "amitriptyline hydrochloride", ["Elavil"], "Tablet", "10 mg, 25 mg, 50 mg, 75 mg, 100 mg", "0006-0428-68", "Psychiatry / Tricyclic Antidepressant (TCA)", True),
    ("Nortriptyline", "nortriptyline hydrochloride", ["Pamelor"], "Capsule", "10 mg, 25 mg, 50 mg, 75 mg", "0078-0402-05", "Psychiatry / Tricyclic Antidepressant (TCA)", True),
    ("Quetiapine", "quetiapine fumarate", ["Seroquel", "Seroquel XR"], "Tablet / Extended-Release Tablet", "25 mg, 50 mg, 100 mg, 200 mg, 300 mg, 400 mg", "0310-0271-10", "Psychiatry / Atypical Antipsychotic (Second-Generation)", True),
    ("Aripiprazole", "aripiprazole", ["Abilify"], "Tablet / Solution / ODT", "2 mg, 5 mg, 10 mg, 15 mg, 20 mg, 30 mg", "59148-006-13", "Psychiatry / Atypical Antipsychotic (Dopamine Partial Agonist)", True),
    ("Olanzapine", "olanzapine", ["Zyprexa", "Zyprexa Zydis"], "Tablet / ODT", "2.5 mg, 5 mg, 7.5 mg, 10 mg, 15 mg, 20 mg", "0002-4115-30", "Psychiatry / Atypical Antipsychotic (Second-Generation)", True),
    ("Risperidone", "risperidone", ["Risperdal", "Risperdal M-Tab"], "Tablet / ODT / Solution", "0.25 mg, 0.5 mg, 1 mg, 2 mg, 3 mg, 4 mg", "50458-301-04", "Psychiatry / Atypical Antipsychotic (Second-Generation)", True),
    ("Lithium Carbonate", "lithium carbonate", ["Lithobid"], "Extended-Release Tablet / Capsule", "150 mg, 300 mg, 450 mg, 600 mg", "0078-0459-05", "Psychiatry / Mood Stabilizer (Bipolar Disorder)", True),
    ("Buspirone", "buspirone hydrochloride", ["Buspar"], "Tablet", "5 mg, 7.5 mg, 10 mg, 15 mg, 30 mg", "0087-0818-41", "Psychiatry / 5-HT1A Agonist Anxiolytic", False),
    ("Hydroxyzine", "hydroxyzine hydrochloride", ["Atarax", "Vistaril"], "Tablet / Capsule", "10 mg, 25 mg, 50 mg", "0069-5430-66", "Psychiatry & Allergy / First-Generation Antihistamine Anxiolytic", False),
    ("Alprazolam", "alprazolam", ["Xanax", "Xanax XR"], "Tablet / Extended-Release Tablet", "0.25 mg, 0.5 mg, 1 mg, 2 mg", "0009-0029-01", "Psychiatry / Benzodiazepine Anxiolytic (C-IV)", True),
    ("Clonazepam", "clonazepam", ["Klonopin"], "Tablet / ODT", "0.5 mg, 1 mg, 2 mg", "0004-0058-01", "Psychiatry & Neurology / Benzodiazepine (C-IV)", True),
    ("Lorazepam", "lorazepam", ["Ativan"], "Tablet / Solution", "0.5 mg, 1 mg, 2 mg", "0008-0064-01", "Psychiatry / Benzodiazepine (C-IV)", True),
    ("Diazepam", "diazepam", ["Valium"], "Tablet / Solution", "2 mg, 5 mg, 10 mg", "0004-0005-01", "Psychiatry / Benzodiazepine (C-IV)", True),
    ("Zolpidem", "zolpidem tartrate", ["Ambien", "Ambien CR"], "Tablet / Extended-Release Tablet", "5 mg, 6.25 mg, 10 mg, 12.5 mg", "0024-5401-31", "Psychiatry / Non-Benzodiazepine Z-Hypnotic (C-IV)", True),
    ("Eszopiclone", "eszopiclone", ["Lunesta"], "Tablet", "1 mg, 2 mg, 3 mg", "63833-191-30", "Psychiatry / Non-Benzodiazepine Z-Hypnotic (C-IV)", True),
    ("Methylphenidate", "methylphenidate hydrochloride", ["Ritalin", "Concerta"], "Tablet / Extended-Release Tablet", "5 mg, 10 mg, 18 mg, 20 mg, 27 mg, 36 mg, 54 mg", "0078-0370-05", "Psychiatry / CNS Stimulant (ADHD, C-II)", True),
    ("Dextroamphetamine/Amphetamine", "dextroamphetamine and amphetamine", ["Adderall", "Adderall XR"], "Tablet / Extended-Release Capsule", "5 mg, 10 mg, 15 mg, 20 mg, 25 mg, 30 mg", "54092-381-01", "Psychiatry / Mixed Amphetamine Salts Stimulant (ADHD, C-II)", True),
    ("Lisdexamfetamine", "lisdexamfetamine dimesylate", ["Vyvanse"], "Capsule / Chewable Tablet", "10 mg, 20 mg, 30 mg, 40 mg, 50 mg, 60 mg, 70 mg", "59417-101-10", "Psychiatry / Amphetamine Prodrug Stimulant (ADHD, C-II)", True),
    ("Atomoxetine", "atomoxetine hydrochloride", ["Strattera"], "Capsule", "10 mg, 18 mg, 25 mg, 40 mg, 60 mg, 80 mg, 100 mg", "0002-3227-30", "Psychiatry / Selective Norepinephrine Reuptake Inhibitor (Non-Stimulant ADHD)", True),

    # 13. Gastrointestinal: PPIs, H2 Blockers, Antiemetics, Motility, IBD
    ("Omeprazole", "omeprazole", ["Prilosec"], "Delayed-Release Capsule", "10 mg, 20 mg, 40 mg", "0186-0602-31", "Gastrointestinal / Proton Pump Inhibitor (PPI)", False),
    ("Pantoprazole", "pantoprazole sodium", ["Protonix"], "Delayed-Release Tablet", "20 mg, 40 mg", "0008-0923-02", "Gastrointestinal / Proton Pump Inhibitor (PPI)", False),
    ("Esomeprazole", "esomeprazole magnesium", ["Nexium"], "Delayed-Release Capsule", "20 mg, 40 mg", "0186-5020-31", "Gastrointestinal / Proton Pump Inhibitor (S-Enantiomer)", False),
    ("Lansoprazole", "lansoprazole", ["Prevacid"], "Delayed-Release Capsule", "15 mg, 30 mg", "0069-1541-30", "Gastrointestinal / Proton Pump Inhibitor (PPI)", False),
    ("Dexlansoprazole", "dexlansoprazole", ["Dexilant"], "Delayed-Release Capsule", "30 mg, 60 mg", "64764-171-30", "Gastrointestinal / Dual Delayed-Release PPI", False),
    ("Famotidine", "famotidine", ["Pepcid"], "Tablet / Oral Suspension", "20 mg, 40 mg", "0006-0964-68", "Gastrointestinal / Histamine-2 (H2) Receptor Antagonist", False),
    ("Ondansetron", "ondansetron hydrochloride", ["Zofran", "Zofran ODT"], "Tablet / ODT / Oral Solution", "4 mg, 8 mg", "0173-0446-00", "Gastrointestinal / 5-HT3 Serotonin Receptor Antagonist Antiemetic", False),
    ("Metoclopramide", "metoclopramide hydrochloride", ["Reglan"], "Tablet / Oral Solution", "5 mg, 10 mg", "0078-0420-05", "Gastrointestinal / Dopamine Antagonist Prokinetic", True),
    ("Promethazine", "promethazine hydrochloride", ["Phenergan"], "Tablet / Oral Syrup / Suppository", "12.5 mg, 25 mg, 50 mg", "0008-0249-01", "Gastrointestinal & Allergy / Phenothiazine Antiemetic", True),
    ("Prochlorperazine", "prochlorperazine maleate", ["Compazine"], "Tablet / Suppository", "5 mg, 10 mg, 25 mg", "0007-3343-20", "Gastrointestinal / Phenothiazine Antiemetic", True),
    ("Dicyclomine", "dicyclomine hydrochloride", ["Bentyl"], "Capsule / Tablet", "10 mg, 20 mg", "58914-010-10", "Gastrointestinal / Anticholinergic Antispasmodic (IBS)", False),
    ("Hyoscyamine", "hyoscyamine sulfate", ["Levsin", "Anaspaz"], "Sublingual Tablet / Elixir", "0.125 mg, 0.375 mg", "68220-112-10", "Gastrointestinal / Anticholinergic Belladonna Alkaloid", False),
    ("Mesalamine", "mesalamine", ["Lialda", "Apriso", "Asacol HD", "Canasa"], "Delayed-Release Tablet / Enema / Suppository", "0.375 g, 0.8 g, 1.2 g", "54092-471-12", "Gastrointestinal / 5-Aminosalicylic Acid (5-ASA) Anti-Inflammatory", False),
    ("Polyethylene Glycol 3350", "polyethylene glycol 3350", ["MiraLAX"], "Oral Powder for Solution", "17 g/dose", "41167-005-01", "Gastrointestinal / Osmotic Laxative", False),
    ("Lactulose", "lactulose", ["Enulose", "Kristalose"], "Oral Solution / Powder Packet", "10 g/15 mL", "0054-8210-25", "Gastrointestinal / Synthetic Disaccharide Osmotic / Hepatic Encephalopathy", False),

    # 14. Analgesics, Musculoskeletal, Rheumatology, Urology & Specialized Outpatient
    ("Ibuprofen", "ibuprofen", ["Advil", "Motrin"], "Tablet / Capsule", "400 mg, 600 mg, 800 mg", "0009-0750-01", "Analgesic & Musculoskeletal / Nonsteroidal Anti-Inflammatory Drug (NSAID)", True),
    ("Naproxen", "naproxen", ["Aleve", "Naprosyn"], "Tablet / Delayed-Release Tablet", "250 mg, 375 mg, 500 mg", "0004-0028-01", "Analgesic & Musculoskeletal / NSAID", True),
    ("Meloxicam", "meloxicam", ["Mobic"], "Tablet / Oral Suspension", "7.5 mg, 15 mg", "0597-0029-01", "Analgesic & Musculoskeletal / COX-2 Preferential NSAID", True),
    ("Celecoxib", "celecoxib", ["Celebrex"], "Capsule", "50 mg, 100 mg, 200 mg, 400 mg", "0025-1520-31", "Analgesic & Musculoskeletal / Selective COX-2 Inhibitor NSAID", True),
    ("Diclofenac Sodium", "diclofenac sodium", ["Voltaren", "Voltaren Gel"], "Delayed-Release Tablet / 1% Topical Gel", "50 mg, 75 mg, 1%", "0078-0437-05", "Analgesic & Musculoskeletal / Acetic Acid NSAID", True),
    ("Indomethacin", "indomethacin", ["Indocin"], "Capsule / Oral Suspension", "25 mg, 50 mg", "0006-0025-68", "Analgesic & Musculoskeletal / Potent NSAID (Gout / Arthritis)", True),
    ("Ketorolac (Oral)", "ketorolac tromethamine", ["Toradol"], "Tablet", "10 mg", "0004-0091-01", "Analgesic & Musculoskeletal / Short-Term Potent NSAID", True),
    ("Tramadol", "tramadol hydrochloride", ["Ultram"], "Tablet / Extended-Release Tablet", "50 mg, 100 mg, 200 mg", "50458-650-60", "Analgesic & Musculoskeletal / Centrally Acting Synthetic Opioid (C-IV)", True),
    ("Hydrocodone/Acetaminophen", "hydrocodone bitartrate and acetaminophen", ["Norco", "Vicodin", "Lortab"], "Tablet", "5/325 mg, 7.5/325 mg, 10/325 mg", "0023-6020-01", "Analgesic & Musculoskeletal / Opioid Agonist + Non-Opioid Combination (C-II)", True),
    ("Oxycodone/Acetaminophen", "oxycodone hydrochloride and acetaminophen", ["Percocet"], "Tablet", "2.5/325 mg, 5/325 mg, 7.5/325 mg, 10/325 mg", "63481-623-70", "Analgesic & Musculoskeletal / Semisynthetic Opioid Combination (C-II)", True),
    ("Morphine Sulfate", "morphine sulfate", ["MS Contin"], "Extended-Release Tablet", "15 mg, 30 mg, 60 mg, 100 mg, 200 mg", "59011-260-10", "Analgesic & Musculoskeletal / Pure Opioid Agonist (C-II)", True),
    ("Buprenorphine/Naloxone", "buprenorphine and naloxone", ["Suboxone"], "Sublingual Film / Tablet", "2/0.5 mg, 4/1 mg, 8/2 mg, 12/3 mg", "12496-1208-1", "Analgesic & Addiction / Partial Opioid Agonist + Antagonist (C-III)", True),
    ("Cyclobenzaprine", "cyclobenzaprine hydrochloride", ["Flexeril"], "Tablet / Extended-Release Capsule", "5 mg, 7.5 mg, 10 mg", "50458-280-10", "Analgesic & Musculoskeletal / Centrally Acting Skeletal Muscle Relaxant", False),
    ("Baclofen", "baclofen", ["Lioresal"], "Tablet", "10 mg, 20 mg", "0078-0093-05", "Analgesic & Musculoskeletal / GABA-B Agonist Skeletal Muscle Relaxant", True),
    ("Tizanidine", "tizanidine hydrochloride", ["Zanaflex"], "Tablet / Capsule", "2 mg, 4 mg", "0254-4155-07", "Analgesic & Musculoskeletal / Alpha-2 Adrenergic Agonist Muscle Relaxant", False),
    ("Methocarbamol", "methocarbamol", ["Robaxin"], "Tablet", "500 mg, 750 mg", "0031-7429-63", "Analgesic & Musculoskeletal / Central Muscle Relaxant", False),
    ("Allopurinol", "allopurinol", ["Zyloprim"], "Tablet", "100 mg, 300 mg", "65483-201-10", "Rheumatology / Xanthine Oxidase Inhibitor (Gout)", False),
    ("Colchicine", "colchicine", ["Colcrys"], "Tablet / Capsule", "0.6 mg", "59762-1199-1", "Rheumatology / Antimitotic Microtubule Disruptor (Gout)", False),
    ("Febuxostat", "febuxostat", ["Uloric"], "Tablet", "40 mg, 80 mg", "64764-918-30", "Rheumatology / Non-Purine Xanthine Oxidase Inhibitor (Gout)", True),
    ("Methotrexate (Oral)", "methotrexate", ["Trexall", "Otrexup"], "Tablet", "2.5 mg, 5 mg, 7.5 mg, 10 mg, 15 mg", "0049-0120-10", "Rheumatology & Oncology / Antifolate Immunosuppressant / DMARD", True),
    ("Hydroxychloroquine", "hydroxychloroquine sulfate", ["Plaquenil"], "Tablet", "200 mg", "0024-1562-10", "Rheumatology / 4-Aminoquinoline Antimalarial / DMARD", False),
    ("Tamsulosin", "tamsulosin hydrochloride", ["Flomax"], "Capsule", "0.4 mg", "0597-0058-01", "Urology / Selective Alpha-1A Adrenergic Antagonist (BPH)", False),
    ("Finasteride", "finasteride", ["Proscar", "Propecia"], "Tablet", "1 mg, 5 mg", "0006-0072-31", "Urology / Type II 5-Alpha Reductase Inhibitor", False),
    ("Dutasteride", "dutasteride", ["Avodart"], "Capsule", "0.5 mg", "0173-0712-00", "Urology / Dual Type I & II 5-Alpha Reductase Inhibitor", False),
    ("Oxybutynin", "oxybutynin chloride", ["Ditropan XL"], "Extended-Release Tablet", "5 mg, 10 mg, 15 mg", "50458-850-90", "Urology / Anticholinergic Antispasmodic (Overactive Bladder)", False),
    ("Solifenacin", "solifenacin succinate", ["Vesicare"], "Tablet", "5 mg, 10 mg", "51248-150-01", "Urology / Competitive M3 Muscarinic Antagonist (OAB)", False),
    ("Mirabegron", "mirabegron", ["Myrbetriq"], "Extended-Release Tablet", "25 mg, 50 mg", "0469-2601-30", "Urology / Beta-3 Adrenergic Agonist (Overactive Bladder)", False),
    ("Sildenafil", "sildenafil citrate", ["Viagra", "Revatio"], "Tablet", "20 mg, 25 mg, 50 mg, 100 mg", "0069-4210-30", "Urology & Cardiovascular / Phosphodiesterase-5 (PDE-5) Inhibitor", False),
    ("Tadalafil", "tadalafil", ["Cialis", "Adcirca"], "Tablet", "2.5 mg, 5 mg, 10 mg, 20 mg", "0002-4462-30", "Urology & Cardiovascular / Phosphodiesterase-5 (PDE-5) Inhibitor", False),
    ("Latanoprost", "latanoprost", ["Xalatan"], "Ophthalmic Solution", "0.005%", "0013-8303-04", "Ophthalmology / Prostaglandin F2-alpha Analog (Glaucoma)", False),
    ("Timolol (Ophthalmic)", "timolol maleate", ["Timoptic"], "Ophthalmic Solution", "0.25%, 0.5%", "0006-3366-35", "Ophthalmology / Non-Selective Beta-Adrenergic Blocker", False),
    ("Brimonidine", "brimonidine tartrate", ["Alphagan P"], "Ophthalmic Solution", "0.1%, 0.15%", "0023-9177-05", "Ophthalmology / Alpha-2 Adrenergic Agonist (Glaucoma)", False),
    ("Dorzolamide/Timolol", "dorzolamide hydrochloride and timolol maleate", ["Cosopt"], "Ophthalmic Solution", "2%/0.5%", "0006-3612-35", "Ophthalmology / Carbonic Anhydrase Inhibitor + Beta Blocker", False),
    ("Prednisolone Acetate (Ophthalmic)", "prednisolone acetate", ["Pred Forte"], "Ophthalmic Suspension", "1%", "0023-0180-05", "Ophthalmology / Ophthalmic Corticosteroid", False),
    ("Mupirocin (Topical)", "mupirocin", ["Bactroban"], "Topical Ointment / Cream", "2%", "0007-4225-22", "Dermatology / RNA Synthetase Inhibitor Topical Antibiotic", False),
    ("Triamcinolone Acetonide (Topical)", "triamcinolone acetonide", ["Kenalog"], "Topical Cream / Ointment", "0.025%, 0.1%, 0.5%", "0003-0414-60", "Dermatology / Medium-to-High Potency Topical Corticosteroid", False),
    ("Clobetasol Propionate", "clobetasol propionate", ["Temovate"], "Topical Cream / Ointment / Solution", "0.05%", "0173-0476-00", "Dermatology / Super-High Potency Topical Corticosteroid", False),
    ("Tretinoin", "tretinoin", ["Retin-A"], "Topical Cream / Gel", "0.025%, 0.05%, 0.1%", "0187-5140-20", "Dermatology / Retinoid Keratolytic (Acne)", False),
    ("Tacrolimus (Systemic / Topical)", "tacrolimus", ["Prograf", "Protopic"], "Capsule / Topical Ointment", "0.5 mg, 1 mg, 5 mg, 0.03%, 0.1%", "0469-0607-73", "Immunology & Dermatology / Calcineurin Inhibitor", True),
    ("Cyclosporine", "cyclosporine (modified)", ["Neoral", "Gengraf", "Restasis"], "Capsule / Oral Solution / Ophthalmic", "25 mg, 100 mg, 0.05%", "0078-0248-34", "Immunology / Calcineurin Inhibitor Immunosuppressant", True),
    ("Mycophenolate Mofetil", "mycophenolate mofetil", ["CellCept"], "Capsule / Tablet / Suspension", "250 mg, 500 mg", "0004-0259-01", "Immunology / Inosine Monophosphate Dehydrogenase Inhibitor", True),
    ("Azathioprine", "azathioprine", ["Imuran"], "Tablet", "50 mg", "65483-590-10", "Immunology / Purine Synthesis Antimetabolite Immunosuppressant", True),
    ("Tamoxifen", "tamoxifen citrate", ["Nolvadex"], "Tablet", "10 mg, 20 mg", "0310-0250-60", "Oncology / Selective Estrogen Receptor Modulator (SERM)", True),
    ("Anastrozole", "anastrozole", ["Arimidex"], "Tablet", "1 mg", "0310-0201-30", "Oncology / Non-Steroidal Aromatase Inhibitor (Breast Cancer)", False),
    ("Letrozole", "letrozole", ["Femara"], "Tablet", "2.5 mg", "0078-0249-15", "Oncology / Non-Steroidal Aromatase Inhibitor (Breast Cancer)", False),
    ("Hydroxyurea", "hydroxyurea", ["Hydrea", "Droxia"], "Capsule", "200 mg, 300 mg, 400 mg, 500 mg", "0003-0830-50", "Hematology & Oncology / Ribonucleotide Reductase Inhibitor", True)
]

print(f"Total Expansion Catalog entries defined: {len(EXPANSION_CATALOG)}")
